Chore/exception compatibility
code42/py42 pull request #180
Opened 2020-08-26 22:07 UTC by alanag13

### Description of Change ###

- removes `Py42UserNotFoundError`. This would be a breaking change for situations where a username did not exist (normally an empty list is returned).
- makes `Py42UserAlreadyAddedError` an instance of `Py42BadRequestError` in order to make exception handling backwards compatible.
- makes `Py42LegalHoldNotFoundOrPermissionDeniedError` an instance of `Py42ForbiddenError` n order to make exception handling backwards compatible.

2020-08-26 22:09 UTC, alanag13 commented on src/py42/exceptions.py
> +class Py42BadRequestError(Py42HTTPError):
These had to be moved up because super classes have to come before their inheritors if they are in the same file

2020-08-27 05:54 UTC, kiran-chaudhary requested changes
The changes seem fine. Need change log for breaking change.

2020-08-27 12:20 UTC, unparalleled-js approved these changes

2020-08-27 12:21 UTC, unparalleled-js commented
> The changes seem fine. Need change log for breaking change.

Oh yeah.  This isn't released, but the CHANGELOG needs to be amended to get rid of the User exception one.

2020-08-27 12:22 UTC, unparalleled-js commented
We could potentially leave User Does Not Exists Exception and just import it other places... There is a strong chance we will need this exception in more places than just the CLI.

2020-08-27 12:23 UTC, unparalleled-js reviewed
Fix Changelog.
Consider allowing `Py42UserDoesNotExists` be importable from py42 yet, even if it not raised anywhere.  If that is the case, make sure it's doc str reflects that.

2020-08-27 12:43 UTC, alanag13 commented
It doesn't make much sense to me to have Py42 define exceptions that it does not raise - I have never imported an exception from a library to raise it, just to catch it.

Thanks for the reminder to edit the change log, I'll do that this morning

2020-08-27 13:59 UTC, merged