Chore/update device settings
code42/py42 pull request #410
Opened 2022-03-28 19:40 UTC by tora-kozic

### Description of Change ###

Adds the `IncydrDeviceSettings` class to manage device settings on computers without backup settings.  Previously, trying to get the device settings of an Incydr machine threw an error because we assume backup configuration values would be provided.

### Testing Procedure ###

Users should be able to use the `DeviceService` methods `get_settings()` and `update_settings()` to view properties and update the _notes_ and _external_reference_ fields on the device settings.

### PR Checklist ###
Did you remember to do the below?

- [x] Add unit tests to verify this change
- [x] Add an entry to CHANGELOG.md describing this change
- [x] Add docstrings for any new public parameters / methods / classes

2022-03-29 17:16 UTC, tora-kozic commented
Upgrading black made a lot of small changes to files - relevant changes are in these
- docs/userguides/devicesettings.md
- src/py42/clients/settings/device_settings.py
- src/py42/services/devices.py
- tests/clients/settings/test_incydr_device_settings.py
- tests/services/test_devices.py

2022-03-29 17:45 UTC, timabrmsn requested changes

2022-03-29 17:45 UTC, timabrmsn commented on src/py42/clients/settings/device_settings.py
> +    """Class used to manage individual Incydr devices.  These devices have no backup settings and are only the **notes** and **external reference** fields are modifiable."""
and ~~are~~ only

2022-03-29 17:45 UTC, timabrmsn commented on src/py42/services/devices.py
> +        print(settings.data)
whoops

2022-03-29 17:45 UTC, timabrmsn commented on tests/clients/settings/test_incydr_device_settings.py
> +    @pytest.mark.parametrize("param", [("notes", None), ("external_reference", None)])
We should add examples with real test strings here too, as we could hypothetically change the implementation to something like:

```
@property
    def notes(self):
        pass
```
and this test would still pass.

2022-03-29 17:45 UTC, timabrmsn commented on tests/services/test_devices.py
> +        # response = """{'computerId': 3985, 'name': '994627866755117009', 'osHostname': 'DESKTOP-I2SKEML', 'guid': '994627866755117009', 'type': 'COMPUTER', 'status': 'Active', 'active': True, 'bloc
probably don't need this line anymore?

2022-03-30 14:15 UTC, timabrmsn approved these changes

2022-03-30 14:51 UTC, merged